Update action.yml

diff --git a/.github/actions/deploy/action.yml b/.github/actions/deploy/action.yml
--- a/.github/actions/deploy/action.yml
+++ b/.github/actions/deploy/action.yml
@@ -84,7 +84,7 @@ runs:
     - name: Undeploy existing app if exists
       shell: bash
       run: |
-        echo "y" | cf undeploy capire.incidents --delete-services --delete-service-keys || echo "App not found or undeploy failed"
+        echo "y" | cf undeploy incidents-testing --delete-services --delete-service-keys || echo "App not found or undeploy failed"
 
     - name: Deploy to Cloud Foundry
       shell: bash
